// ES lang variables

tinyMCE.addToLang('media',{
title : 'Insertar / editar archivos multimedia embebidos',
desc : 'Insertar / editar archivos multimedia embebidos',
general : 'General',
advanced : 'Avanzado',
file : 'Archivo',
list : 'Lista',
size : 'Dimensiones',
preview : 'Previsualización',
constrain_proportions : 'Mantener proporciones',
type : 'Tipo',
id : 'Identificador',
name : 'Nombre',
class_name : 'Clase',
vspace : 'V-Space',
hspace : 'H-Space',
play : 'Reproducción automática',
loop : 'Repetir',
menu : 'Mostrar menu',
quality : 'Calidad',
scale : 'Escala',
align : 'Alinear',
salign : 'SAlign',
wmode : 'WMode',
bgcolor : 'Color de fondo',
base : 'Base',
flashvars : 'Flashvars',
liveconnect : 'SWLiveConnect',
autohref : 'AutoHREF',
cache : 'Cache',
hidden : 'Oculto',
controller : 'Controlador',
kioskmode : 'Modo Kiosko',
playeveryframe : 'Reproducir todos los frames',
targetcache : 'Target cache',
correction : 'Sin corrección',
enablejavascript : 'Permitir JavaScript',
starttime : 'Tiempo de comienzo',
endtime : 'Tiempo de fin',
href : 'Href',
qtsrcchokespeed : 'Choke speed',
target : 'Target',
volume : 'Volumen',
autostart : 'Comienzo automático',
enabled : 'Habilitado',
fullscreen : 'Pantalla completa',
invokeurls : 'Invocar URLs',
mute : 'Sin sonido',
stretchtofit : 'Ajustar',
windowlessvideo : 'Windowless video',
balance : 'Balance',
baseurl : 'URL Base',
captioningid : 'Captioning id',
currentmarker : 'Marcador actual',
currentposition : 'Posición actual',
defaultframe : 'Frame por defecto',
playcount : 'Cuenta de reproducción',
rate : 'Rate',
uimode : 'UI Mode',
flash_options : 'Opciones Flash',
qt_options : 'Opciones Quicktime',
wmp_options : 'Opciones Windows Media',
rmp_options : 'Opciones Real Media',
shockwave_options : 'Opciones Shockwave',
autogotourl : 'Ir a URL automáticamente',
center : 'Centrar',
imagestatus : 'Estado de imagen',
maintainaspect : 'Mantener aspecto',
nojava : 'Sin java',
prefetch : 'Prefetch',
shuffle : 'Aleatorio',
console : 'Consola',
numloop : 'Número de repeticiones',
controls : 'Controles',
scriptcallbacks : 'Llamadas a scripts',
swstretchstyle : 'Estilo de ajuste',
swstretchhalign : 'Ajuste H-Align',
swstretchvalign : 'Ajuste V-Align',
sound : 'Sonido',
progress : 'Progreso',
qtsrc : 'QT Src',
qt_stream_warn : 'Los recursos rstp deben añadirse en el campo QT Src en la pestaña de características avanzadas.\nDebería añadirse también una versión no streaming en el campo Src.'
});
